### ISSUE TITLE
No documentation.

### ISSUE THREAD

**Issue by alejandrojapkin** [KaroDievas/car-sound-classification-with-keras#1]
Your project seems interesting. Is it actually public ? There's absolutely no documentation on how to run it.

**Comment by KaroDievas** [comment]
Hello, 
It's glad to know that my project is interesting. 
So talking about project it's under MIT license. Actually I am writing master's degree thesis of "Object detection in audio stream" so this project about it just shorten to car engine sounds.
About system:
I am running it on ubuntu 16.04 LTS. I try to write proper documentation, how to run it.

**Comment by alejandrojapkin** [comment]
For instance, Predictor.py has these args

img_path = sys.argv[1]
weights =  sys.argv[2]

Would you mind telling what the second arg should look like? Your current readme is wrong
