### ISSUE TITLE
TrainModel.py Errors

### ISSUE THREAD

**Issue by logicmohe** [KaroDievas/car-sound-classification-with-keras#4]
Hi there,

I'm trying to use my Raspberry Pi to build a sound classifier based on your project. I got some trouble while trying to run the TrainModel.py after Main.py finished

- K.set_image_dim_ordering("th") I searched forum and it's version problem. Replace it with K.image_data_format()=='channels_first' and it works
--Then I got errors at line 22: Model = kerasModel.get_model(img_width,img_height)
shows valueError: Negative dimension size caused by subtracting 2 from 1 fro 'max_pooling2d_1/MaxPool' (op:'MaxPool')with input shapes: [?,1,501,32]

Could you help me with that? I used around 200 samples and already change the number of train samples and validation samples

**Comment by KaroDievas** [comment]
Hello, 

Did you changed some layers ? It might be issue with yours initial sample dimensions. 
Keep in mind that I used img_width, img_height = 503, 376 
So these values should be changed with respect of current sample dimensions you have

Also is raspeberry pi not to slow for deep learning applications ?

**Comment by logicmohe** [comment]
Hi Karo,

Not sure what size of img I should change to. The samples I have is 48,000 Hz 2 seconds wav audio file. I didn't find any corresponding figures online.

Well, although I am using a 3B, but only 400 samples shouldn't be a problem.

Here is the error I got while running Main.py on an Ubuntu server
![image](https://user-images.githubusercontent.com/46504798/69891019-c0c6b680-12cf-11ea-8833-6d3f0b765d52.png)

Any advice?

**Comment by KaroDievas** [comment]
Well it seems like you should install sndfile library. Did you try that ?

**Comment by logicmohe** [comment]
Oh yeah, sorry I made a stupid mistake.
Result of Main.py:
![image](https://user-images.githubusercontent.com/46504798/69995528-a0446980-1526-11ea-97d1-9da6a5403c6f.png)
Result of TrainModel.py:
![image](https://user-images.githubusercontent.com/46504798/69995599-c36f1900-1526-11ea-8e46-ff9320498cd4.png)

Back to the previous question, I'm using 48e3 Hz of audio file with 2s. Any idea what size of img I should set to?

Thanks

**Comment by KaroDievas** [comment]
secondly you should install ffmpeg. Did you read readme.md ? 
You should convert your audio file to and spertrum image file and write down dimmensions

**Comment by logicmohe** [comment]
Hi Karo, yeah I did install ffmpeg as Requirements in readme.md. But no clue why it shows that. Anyway, don't bother it, I turn to use other methods. Thanks for your help!
