### ISSUE TITLE
Categorizing the Original Audio Files

### ISSUE THREAD

**Issue by xuhaoteoh** [KaroDievas/car-sound-classification-with-keras#5]
Hi, may I know if how shall I categorize the original source of audio? And where do you get these original source of audio? 

I hope I get your help guidance as I am doing this for my Final Year Project and I am a newbie in deep learning.

Thanks in advance.

**Comment by KaroDievas** [comment]
Hi, 

You can collect any type of audio. Of cource it should be of same type and same quality. For example you can collect only petrol car engine sounds.
I have used simple smart phone recorder. Records can be categorized by some type, in my case it was car.
Later on you should transform your audio source to image. I have used wavelet sound explorer. 
Then you can teach network

**Comment by xuhaoteoh** [comment]
Hi,

I have noticed you have added original sources of your audio files in the Data file. How can I make good use of them?

**Comment by KaroDievas** [comment]
These files must be converted to spertrum images. I have used wavelet sound explorer
